### ISSUE TITLE
Error: OOM when allocating tensor with shape[16,256,52,52] when using python3

### ISSUE THREAD

**Issue by illw84u** [experiencor/keras-yolo3#58] opened 2018-05-15 03:35 UTC
got another error : pickle protocol: 4 when using python2

is this due to the version of python?

**Comment by RichardSieg** [comment] 2018-05-15 07:46
You have an out of memory error. This is probably caused by a too large batch size. Try a smaller one.

**Comment by illw84u** [comment] 2018-05-16 01:29
Thanks, changing batch size from 16 to 4 solved the oom issue.

**Comment by RichardSieg** [comment] 2018-05-16 08:29
Great. Please close the issue then :)

**Closed** 2018-05-16 09:08 UTC
